### ISSUE TITLE
Google advice on tabindex

### ISSUE THREAD

**Issue by Byham2012** [pojome/one-click-accessibility#81]
I think the plugin is wonderful but Google just to throw a spanner in the works says, 
"A value greater than 0 implies an explicit navigation ordering. Although technically valid, this often creates frustrating experiences for users who rely on assistive technologies."
<a id="pojo-a11y-skip-content" class="pojo-skip-link pojo-skip-content" tabindex="1" accesskey="s" href="#content">

just letting you know :)

**Comment by sasgrw** [comment]
Looks like this might have been fixed?  I see `tabindex="0"` on all the links now, which is superfluous because links are naturally keyboard focusable (unless they don't have an HREF attribute).  All the links have `role="link"` which is also superfluous.  But the original comment by @Byham2012 seems to be fixed.

**Comment by JBrady** [comment]
This issue seems to be back in version 2.1.0. Although that may be by design. I got this explanation from ChatGPT4...

_The "skip to content" link in the One Click Accessibility plugin, or any other similar plugin, may have a tabindex attribute greater than 0 to ensure that it is the first element that receives focus when users navigate the page using the keyboard. By setting a positive tabindex value, developers can explicitly control the order in which focus moves through the elements on the page._

_In general, it's recommended to avoid using positive tabindex values to maintain the natural tab order based on the order of elements in the HTML markup. However, in the case of "skip to content" links, the intention is to make the link easily accessible to keyboard users. By setting the tabindex to a value greater than 0, the "skip to content" link becomes the first focusable element on the page when users start tabbing through the page elements._

_It's essential to keep in mind that using positive tabindex values should be done with caution, as doing so can interfere with the expected tab order and negatively impact accessibility. In this specific case, the choice to use a positive tabindex value is made to improve the user experience for keyboard users who rely on the "skip to content" functionality._

Could be incorrect, but it seems reasonable.

**Comment by Byham2012** [comment]
Thank you. I’ll check it out ☺️

Tanya Byham
0410 801 462


On 17 Mar 2023, at 10:50, John Brady ***@***.***> wrote:

﻿

This issue seems to be back in version 2.1.0. Although that may be by design. I got this explanation from ChatGPT4...

The "skip to content" link in the One Click Accessibility plugin, or any other similar plugin, may have a tabindex attribute greater than 0 to ensure that it is the first element that receives focus when users navigate the page using the keyboard. By setting a positive tabindex value, developers can explicitly control the order in which focus moves through the elements on the page.

In general, it's recommended to avoid using positive tabindex values to maintain the natural tab order based on the order of elements in the HTML markup. However, in the case of "skip to content" links, the intention is to make the link easily accessible to keyboard users. By setting the tabindex to a value greater than 0, the "skip to content" link becomes the first focusable element on the page when users start tabbing through the page elements.

It's essential to keep in mind that using positive tabindex values should be done with caution, as doing so can interfere with the expected tab order and negatively impact accessibility. In this specific case, the choice to use a positive tabindex value is made to improve the user experience for keyboard users who rely on the "skip to content" functionality.

Could be incorrect, but it seems reasonable.
